name: media_picker
description: Flutter plugin to get pictures and videos from the device. It allows you to select one or more images from gallery or camera, without needing to switch provider.
version: 1.3.3
homepage: https://github.com/d-silveira/flutter_media_picker

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mediaspicker
        pluginClass: MediasPickerPlugin
      ios:
        pluginClass: MediasPickerPlugin

environment:
  sdk: ">=1.19.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.10.0 <2.0.0"

